=== boycao/ComicWorld/XMLandXSD/ComicBookBase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="comicbookBase">
        <xs:complexType>  
            <xs:sequence>
                <xs:element name="about">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="title"/>
                            <xs:element name="author"/>
                            <xs:element ref="description"/>
                            <xs:element name="sourceDefs">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="sourceDef">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element ref="title"/>
                                                    <xs:element name="url"/>
                                                    <xs:element ref="description"/>
                                                </xs:sequence>
                                                <xs:attribute ref="id" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="comicbooks">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="comicbook" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="title"/>
                                        <xs:element ref="description"/>
                                        <xs:element name="specs">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="author"  type="xs:string" maxOccurs="unbounded"/>
                                                    <xs:element name="year" type="xs:string"/>
                                                    <xs:element name="publisher"  type="xs:string" maxOccurs="unbounded"/>
                                                    <xs:element name="coverType" type="xs:string"/>
                                                    
                                                    <xs:element name="language" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="series"  type="xs:string" maxOccurs="unbounded"/>
                                        <xs:element name="images">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="image" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute name="filename" type="xs:anyURI"
                                                                use="required"/>
                                                            <xs:attribute name="caption" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="comments">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element maxOccurs="unbounded"
                                                        name="comment" minOccurs="0">
                                                        <xs:complexType mixed="true">
                                                            <xs:attribute name="rating"  use="required"/>
                                                            <xs:attribute name="author" type="xs:string"
                                                                use="required"/>
                                                            <xs:attribute name="new" type="xs:boolean"  use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="rating">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:float">
                                                    <xs:minInclusive value="0.1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="price">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:float">
                                                    <xs:minInclusive value="0.01"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="storage">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="sources">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element maxOccurs="unbounded"
                                                        name="sourceRefId" type="xs:IDREF"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="relatedComicbooks">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element maxOccurs="unbounded" ref="comicbookRefId"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute ref="id" use="required"/>
                                    
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="category">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="series">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="title"/>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            name="itemRefId" type="xs:IDREF"/>
                                        <xs:element maxOccurs="unbounded" minOccurs="0"
                                            name="series"/>
                                    </xs:sequence>
                                    <xs:attribute ref="id"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="outieIndex">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="keyword">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="title"/>
                                        <xs:element maxOccurs="unbounded" name="sectionRefId"
                                            type="xs:IDREF"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sequences">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="sequence">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" ref="comicbookRefId"/>
                                    </xs:sequence>
                                    <xs:attribute name="title" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="title" type="xs:string"/>
    <xs:element name="description">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="p">
                    <xs:complexType mixed="true">
                        <xs:group maxOccurs="unbounded" ref="inline"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ul">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="li">
                                <xs:complexType mixed="true">
                                    <xs:group maxOccurs="unbounded" ref="inline"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:attribute name="id" type="xs:ID"/>
    <xs:group name="block">
        <xs:choice>
            <xs:element name="media">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="title"/>
                        <xs:element minOccurs="0" name="caption">
                            <xs:complexType mixed="true">
                                <xs:group maxOccurs="unbounded" minOccurs="0" ref="inline"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute ref="id" use="required"/>
                    <xs:attribute name="url" type="xs:string" use="required"/>
                    <xs:attribute name="type" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:NMTOKEN">
                                <xs:enumeration value="imageWeb"/>
                                <xs:enumeration value="imageLocal"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="style" type="xs:string"/>
                </xs:complexType>
            </xs:element>
        </xs:choice>
    </xs:group>
    <xs:group name="inline">
        <xs:choice>
            <xs:element minOccurs="0" ref="b"/>
            <xs:element minOccurs="0" ref="i"/>
        </xs:choice>
    </xs:group>
    <xs:element name="b"/>
    <xs:element name="i"/>
    <xs:element name="comicbookRefId" type="xs:IDREF"/>
</xs:schema>

=== boycao/ComicWorld/XMLandXSD/ComicBookBase.xml
<?xml version="1.0" encoding="UTF-8"?>
<comicbookBase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ComicBookBase.xsd">
    <about>
        <title>COMIC BOOKS</title>
        <author>
            <name>Boya Cao</name>
        </author>
        <description>
            <p>This is a website contains information about <b>comic books</b> with different
                <i>series</i></p>
            <p>Such as:</p>
            <ul>
                <li><b><i>1.DC</i></b></li>
                <li><b><i>2.Marvel</i></b></li>
            </ul>
        </description>
        <sourceDefs>
            <sourceDef id="sBowie">
                <title>BOWIE: Stardust, Rayguns, and Moonage Daydreams</title>
                <url>https://www.amazon.com/BOWIE-Stardust-Rayguns-Moonage-Daydreams/</url>
                <description>
                    <p>Bowie Source</p>
                </description>
            </sourceDef>
            <sourceDef id="sIG">
                <title>Infinity Gauntlet</title>
                <url>https://www.amazon.com/Infinity-Gauntlet-Marvel-Premiere-Classic/</url>
                <description>
                    <p>Infinity Gauntlet Source</p>
                </description>
            </sourceDef>
            <sourceDef id="sJoker">
                <title>Joker</title>
                <url>https://www.amazon.com/Joker-Black-Label-Brian-Azzarello/</url>
                <description>
                    <p>Joker Source</p>
                </description>
            </sourceDef>
            <sourceDef id="sWoA">
                <title>Women of Action</title>
                <url>https://www.amazon.com/DC-Women-Action-Shea-Fontana/</url>
                <description>
                    <p>Women of Action Source</p>
                </description>
            </sourceDef>
            <sourceDef id="sFlashpoint">
                <title>Flashpoint</title>
                <url>https://www.amazon.com/Flashpoint-Geoff-Johns-ebook/</url>
                <description>
                    <p>Flashpoint Source</p>
                </description>
            </sourceDef>
            <sourceDef id="sSpiderman">
                <title>Spiderman</title>
                <url>https://www.amazon.com/Spider-Man-Miles-Morales-Vol-1/</url>
                <description>
                    <p>Spiderman Source</p>
                </description>
            </sourceDef>
            <sourceDef id="sBatman">
                <title>Batman: White Knight</title>
                <url>https://www.amazon.com/Batman-White-Knight-Sean-Murphy/</url>
                <description>
                    <p>Batman: White Knight Source</p>
                </description>
            </sourceDef>
            <sourceDef id="sBatmanYO">
                <title>Batman:Year One</title>
                <url>https://www.amazon.com/Batman-Year-One-Frank-Miller-ebook/</url>
                <description>
                    <p>Batman:Year OneBatman Source</p>
                </description>
            </sourceDef>
            <sourceDef id="sMinecraft">
                <title>Minecraft</title>
                <url>https://www.amazon.com/Minecraft-Graphic-Novel-Sf%C3%88-M/</url>
                <description>
                    <p>Minecraft Source</p>
                </description>
            </sourceDef>
            <sourceDef id="sEncyclopedia">
                <title>Marvel Encyclopedia</title>
                <url>https://www.amazon.com/Marvel-Encyclopedia-New-Stan-Lee/dp/1465478906/</url>
                <description>
                    <p>Marvel Encyclopedia Source</p>
                </description>
            </sourceDef>
            <sourceDef id="sECH">
                <title>The Essential Calvin and Hobbes: A Calvin and Hobbes Treasury</title>
                <url>https://www.amazon.com/Essential-Calvin-Hobbes-Treasury-ebook/</url>
                <description>
                    <p>The Essential Calvin and Hobbes Source</p>
                </description>
            </sourceDef>
            <sourceDef id="sStarWar">
                <title>Star Wars Vol. 1: Skywalker Strikes </title>
                <url>https://www.amazon.com/Star-Wars-Vol-Skywalker-Strikes-ebook/dp/B0153WYYEW/</url>
                <description>
                    <p>Star Wars Vol. 1: Skywalker Strikes Source</p>
                </description>
            </sourceDef>
            <sourceDef id="sUM">
                <title>Ultimate Marvel </title>
                <url>https://www.amazon.com/Ultimate-Marvel-Adam-Bray/</url>
                <description>
                    <p>Ultimate Marvel Source</p>
                </description>
            </sourceDef>
            <sourceDef id="sHulk">
                <title>Hulk</title>
                    <url>https://www.amazon.com/Immortal-Hulk-Vol-Breaker-Worlds/</url>
                <description>
                    <p>Hulk Source</p>
                </description>
            </sourceDef>
            <sourceDef id="sSuperman">
                <title>All-Star Superman</title>
                <url>https://www.amazon.com/All-Star-Superman-DC-Black-Label/</url>
                <description>
                    <p>All-Star Superman Source</p>
                </description>
            </sourceDef>
        </sourceDefs>
    </about>
    <comicbooks>
        <comicbook id="cb1">
            <title>BOWIE: Stardust, Rayguns, and Moonage Daydreams</title>
            <description>
                <p>Inspired by the legendary David Bowie, BOWIE: Stardust, Rayguns,
                    and Moonage Daydreams is the original graphic memoir of the great
                    Ziggy Stardust!</p>
                <p>This graphic novel chronicles the rise of Bowie's career from 
                    obscurity to fame; and paralleled by the rise and fall of his alter 
                    ego as well as the rise and fall of Ziggy Stardust. As the Spiders 
                    from Mars slowly implode, Bowie wrestles with his Ziggy persona. 
                    The outcome of this internal conflict will change not only David Bowie, 
                    but also, the world. </p>
                <p>
                    <i><b>MASSIVELY SUCCESSFUL GRAPHIC NOVEL OF 2020</b>: A New York Times Best Seller</i>
                    <i><b>CELEBRITY COLLABORATION</b>: Foreword by Neil Gaiman</i>
                    <i><b>SUPERSTAR ARTIST</b>: Illustrated by Michael Allred</i>
                    <i><b>CRITICALLY ACCLAIMED! "The Allreds’ art and love for Bowie’s work makes this one stand apart." </b> – Entertainment Weekly</i>
                    <i><b>STAR-STUDDED</b>: Read of Bowie’s encounters with Elton John, Mark Bolan, The Rolling Stones, Elvis Presley, Jimi Hendrix, and more</i>
                </p>
            </description>
            <specs>
                <author>Michael Allred, Steve Horton</author>
                <year>2020</year>
                <publisher>DC Comics</publisher>
                <coverType>HardCover</coverType>
                <language>English</language>
            </specs>
            <series>DC</series>
            <images>
                <image filename="images/ComicBook/Bowie.jpg" caption="cover"/>
            </images>
            <comments>
                <comment new="true" rating="4" author="Mike"> This is a great book</comment>
                <comment new="false" rating="5" author="Jenny">I love this book</comment>
            </comments>
            <rating>4.5</rating>
            <price>25.99</price>
            <storage>100</storage>
            <sources>
                <sourceRefId>sBowie</sourceRefId>
            </sources>
            <relatedComicbooks>
                <comicbookRefId>cb3</comicbookRefId>
                <comicbookRefId>cb4</comicbookRefId>
                <comicbookRefId>cb5</comicbookRefId>
                <comicbookRefId>cb7</comicbookRefId>
                <comicbookRefId>cb8</comicbookRefId>
                <comicbookRefId>cb15</comicbookRefId>
            </relatedComicbooks>
        </comicbook>
        <comicbook id="cb2">
            <title>Infinity Gauntlet</title>
            <description>
                <p>For the dark Titan Thanos, the Infinity Gauntlet was the Holy Grail, 
                    the ultimate prize to be coveted above all else. With it came omnipotence: 
                    the absolute control of all aspects of time, space, power, reality, 
                    the mind, and the soul. The gaining of supreme might mean the beginning 
                    of a black nightmare for the entire universe. Now, on the edge of 
                    Armageddon and led by the mysterious Adam Warlock, Earth's super heroes
                    join in a desperate attempt to thwart this nihilistic god's insane plunge 
                    into galactic self-destruction. Should the heroes fail, the astral gods of 
                    the universe wait to step into the fray. But in such an awesome cosmic 
                    conflict will anyone prevail? Will anyone survive?</p>
            </description>
            
            <specs>
                <author>Jim Starlin, George Perez</author>
                <year>2010</year>
                <publisher>Marvel</publisher>
                <coverType>HardCover</coverType>
                <language>English</language>
            </specs>
            <series>Marvel</series>
            <images>
                <image filename="images/ComicBook/InfinityGauntlet.jpg" caption="cover"/>
            </images>
            <comments>
                <comment new="true" rating="4" author="Mike"> This is a great book</comment>
                <comment new="false" rating="5" author="Jenny">I love this book</comment>
            </comments>
            <rating>4.5</rating>
            <price>31.42</price>
            <storage>100</storage>
            <sources>
